import { Nations } from "./nations";
import { Planets } from "./planets";
import { Star } from "./types";

export enum STAR_TYPE {
  Capital = "Столица",
  Controlled = "Контролируемая",
  Controversial = "Спорная",
}

/**
 * Звёзды
 * При добавлении новой зезды, её позицию можно задать с помощью координат внизу карты
 * Банально навести курсор куда надо, и запомнить координаты, после чего ввести из звезде.
 *
 * Про поля:
 * * name - Название звезды
 * * description - Описание звезды
 * * planets - Планеты звезды. Необязательное поле. Все планеты находятся в файле planets.ts
 * * affiliation - Фракция которой принадлежит звезда. Все фракции находятся в файле nations.ts
 * * occupiedBy - Фракция которая заняла систему. Создаёт штриховку цвета захватчика и красит систему, при этом система остаётся в зоне affiliation пост-фактум
 * * type - Тип звезды. Все типы находятся выше...
 * * position - Координаты звезды
 * * labelShift - Смещение надписи. Используется для её корректировкиЮ дабы избежать наложения текста. Необязательно
 */
export const Stars: Star[] = [
  {
    name: "Солнце",
    description:
      "Звезда Солнечной системы - колыбели человечества. Является политическим, культурным и экономическим центром Транс-Солнечной Федерации, а также одним из наиболее заселенных и развитых миров человеческого космоса.",
    planets: [
      Planets.Venus,
      Planets.Earth,
      Planets.Moon,
      Planets.Mars,
      Planets.Ganimed,
      Planets.Europe,
      Planets.Titan,
      Planets.Pluto,
    ],
    affiliation: Nations.TSF,
    type: STAR_TYPE.Capital,
    position: { x: 512, y: 512 },
  },
  {
    name: "HD 7924",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 479, y: 58 },
  },
  {
    name: "Кастор",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 581, y: 78 },
  },
  {
    name: "Ι Часов",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 645, y: 50 },
  },
  {
    name: "ρ Кормы",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 675, y: 114 },
  },
  {
    name: "A 2329",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 698, y: 35 },
  },
  {
    name: "Глизе 200",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 777, y: 18 },
    labelShift: { x: 0, y: 5 },
  },
  {
    name: "10 Гончих Псов",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 837, y: 84 },
  },
  {
    name: "37 Близнецов",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 888, y: 129 },
  },
  {
    name: "Ψ Возмичего",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 823, y: 135 },
  },
  {
    name: "104 Тельца",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 812, y: 195 },
  },
  {
    name: "Глизе 156",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 760, y: 152 },
  },
  {
    name: "Глизе 818",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 743, y: 197 },
  },
  {
    name: "9 Кормы",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 970, y: 94 },
  },
  {
    name: "15 Стрелы",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 974, y: 163 },
  },
  {
    name: "β Кассиопеи",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 914, y: 237 },
  },
  {
    name: "10 Большой Медведицы",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 931, y: 297 },
  },
  {
    name: "Глизе 247",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 974, y: 324 },
  },
  {
    name: "51 Пегаса",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 919, y: 357 },
  },
  {
    name: "η Волопаса",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 812, y: 368 },
  },
  {
    name: "β Девы",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 747, y: 363 },
  },
  {
    name: "δ Треугольника",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 779, y: 450 },
  },
  {
    name: "142 Скорпиона",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 713, y: 433 },
  },
  {
    name: "Глизе 570",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 666, y: 453 },
  },
  {
    name: "36 Змееносца",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 675, y: 496 },
  },
  {
    name: "Росс 104",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 661, y: 363 },
  },
  {
    name: "Глизе 300",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 632, y: 325 },
  },
  {
    name: "107 Рыб",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 567, y: 313 },
  },
  {
    name: "Σ Дракона",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 568, y: 373 },
  },
  {
    name: "70 Змееносца",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 610, y: 419 },
  },
  {
    name: "85 Пегаса",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Capital,
    position: { x: 845, y: 536 },
  },
  {
    name: "111 Тельца",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 905, y: 554 },
  },
  {
    name: "G 239",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 812, y: 581 },
  },
  {
    name: "δ Козерога",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 824, y: 630 },
  },
  {
    name: "L 449 - 1",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 794, y: 679 },
  },
  {
    name: "11 Малого льва",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Capital,
    position: { x: 752, y: 751 },
  },
  {
    name: "HR 6806",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 726, y: 295 },
  },
  {
    name: "β Волос Вероники",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 657, y: 206 },
  },
  {
    name: "Демебола",
    affiliation: Nations.Gray,
    occupiedBy: Nations.Imperium,
    type: STAR_TYPE.Capital,
    position: { x: 526, y: 203 },
  },
  {
    name: "Грей μ",
    affiliation: Nations.Gray,
    occupiedBy: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 478, y: 146 },
  },
  {
    name: "Мауна β",
    affiliation: Nations.Gray,
    occupiedBy: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 563.5, y: 181 },
  },
  {
    name: "Глизе 532",
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
    position: { x: 588.5, y: 126 },
  },
  {
    name: "α Центавра",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 530, y: 486 },
  },
  {
    name: "Бернарда",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 561, y: 519 },
  },
  {
    name: "Лаланд",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 497, y: 438 },
    labelShift: { x: 0, y: 2 },
  },
  {
    name: "Росс 128",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 509, y: 416 },
  },
  {
    name: "Вольф 359",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 483, y: 451 },
    labelShift: { x: -10, y: 0 },
  },
  {
    name: "Сириус",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 439, y: 492 },
  },
  {
    name: "Процион",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 413, y: 477 },
  },
  {
    name: "Росс 614",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 398, y: 505 },
  },
  {
    name: "Лакайль 5352",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 530, y: 613 },
    labelShift: { x: 5, y: -17 },
  },
  {
    name: "Крюгер 60",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 552, y: 630 },
    labelShift: { x: 2.5, y: 2.5 },
  },
  {
    name: "Лакайль 8760",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 590, y: 615 },
    labelShift: { x: 7.5, y: 5 },
  },
  {
    name: "Альтаир",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 615, y: 589 },
  },
  {
    name: "61 Лебедя",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 573, y: 587 },
    labelShift: { x: 4, y: -4 },
  },
  {
    name: "ε Индейца",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 556, y: 604 },
    labelShift: { x: -5, y: 4 },
  },
  {
    name: "Росс 154",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 589, y: 538 },
    labelShift: { x: 0, y: -7 },
  },
  {
    name: "Струнве 2398",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 618, y: 543 },
  },
  {
    name: "κ Кита",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Capital,
    position: { x: 748, y: 566 },
  },
  {
    name: "Глизе 667",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controversial,
    position: { x: 671, y: 628 },
  },
  {
    name: "Фомальгаут",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controversial,
    position: { x: 712, y: 611 },
  },
  {
    name: "π Ориона",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controversial,
    position: { x: 730, y: 519 },
  },
  {
    name: "Каптейна",
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
    position: { x: 402, y: 540 },
  },
  {
    name: "ε Эридана",
    affiliation: Nations.Nanotrasen,
    type: STAR_TYPE.Controlled,
    position: { x: 436, y: 559 },
    labelShift: { x: 7.5, y: 0 },
  },
  {
    name: "τ Кита",
    affiliation: Nations.Nanotrasen,
    type: STAR_TYPE.Controlled,
    position: { x: 458, y: 584 },
  },
  {
    name: "Гумбридж 34",
    affiliation: Nations.Nanotrasen,
    type: STAR_TYPE.Controlled,
    position: { x: 507, y: 618 },
    labelShift: { x: -17.5, y: 0 },
  },
  {
    name: "Ψ Змеи",
    affiliation: Nations.Free,
    type: STAR_TYPE.Capital,
    position: { x: 265, y: 211 },
  },
  {
    name: "Глизе 282",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
    position: { x: 266.5, y: 277 },
  },
  {
    name: "μ Жертвенника",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
    position: { x: 226.5, y: 177 },
  },
  {
    name: "Чалаван",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
    position: { x: 321.5, y: 209.5 },
  },
  {
    name: "η Цефея",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
    position: { x: 201, y: 243 },
  },
  {
    name: "Глизе 488",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
    position: { x: 683, y: 768 },
  },
  {
    name: "Гумбридж 1831",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
    position: { x: 658, y: 709 },
  },
  {
    name: "54 Рыб",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
    position: { x: 608, y: 783 },
  },
  {
    name: "41 Жертвенника",
    affiliation: Nations.Unathi,
    type: STAR_TYPE.Capital,
    position: { x: 491, y: 279 },
  },
  {
    name: "HR 753",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 410, y: 302 },
  },
  {
    name: "AD Льва",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 402, y: 366 },
  },
  {
    name: "Глизе 1",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 445, y: 380 },
  },
  {
    name: "ADS 48",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 380, y: 246 },
  },
  {
    name: "G 192-13",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 363, y: 321 },
  },
  {
    name: "γ Зайца",
    affiliation: Nations.Free,
    type: STAR_TYPE.Capital,
    position: { x: 270, y: 381 },
  },
  {
    name: "Тигардена",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 410, y: 410 },
  },
  {
    name: "HD 4391",
    affiliation: Nations.Free,
    type: STAR_TYPE.Capital,
    position: { x: 352, y: 459 },
  },
  {
    name: "20 LMi",
    affiliation: Nations.Free,
    type: STAR_TYPE.Capital,
    position: { x: 336, y: 567 },
  },
  {
    name: "Глизе 433",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 294, y: 587 },
  },
  {
    name: "HR 1614",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 295, y: 628 },
  },
  {
    name: "WISE 0325",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 239, y: 647 },
  },
  {
    name: "Глизе 902",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 163, y: 662 },
  },
  {
    name: "HOP 57050",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 261, y: 707 },
  },
  {
    name: "L 43-72",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 205, y: 732 },
  },
  {
    name: "41 Орла",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 242, y: 783 },
  },
  {
    name: "ν Феникса",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 296, y: 844 },
  },
  {
    name: "OU Близнецов",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 389, y: 838 },
  },
  {
    name: "Глизе 52",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 479, y: 854 },
  },
  {
    name: "Глизе 3825",
    affiliation: Nations.Free,
    type: STAR_TYPE.Capital,
    position: { x: 542, y: 842 },
  },
  {
    name: "ν Волка",
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
    position: { x: 538, y: 799 },
  },

  {
    name: "Арктур",
    description:
      "Звезда одноименной системы, ярчайшая в системе Волопаса. Конечная точка маршрута ковчега “Новая Надежда”, на борту которого находились первые колонисты будущей Республики Эллизиум.",
    planets: [Planets.Tellurus],
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Capital,
    position: { x: 202, y: 501 },
  },
  {
    name: "α Ворона",
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Capital,
    position: { x: 153, y: 612 },
  },
  {
    name: "Глизе 42",
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Controlled,
    position: { x: 151, y: 449 },
  },
  {
    name: "DE Волопаса",
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Controlled,
    position: { x: 211, y: 449 },
  },
  {
    name: "δ Эридана",
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Controlled,
    position: { x: 286, y: 448 },
  },
  {
    name: "FL Водолея",
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Controlled,
    position: { x: 274, y: 539 },
  },
  {
    name: "TRAPPIST 1",
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Controlled,
    position: { x: 193, y: 569 },
  },
  {
    name: "Оплот",
    description:
      "Звезда одноименной системы, ранее известная как Беллатрикс – третья по яркости звезда в созвездии Ориона. По итогам Советской войны за Независимость, объявлена столичной системой СССП (ныне - Коммунистический Союз Социалистических Планет) и главным символом борьбы Галактического пролетариата за светлое будущее.",
    planets: [Planets.Lasarys, Planets.Pioneer, Planets.Pioneer1, Planets.Udarnyik],
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Capital,
    position: { x: 410, y: 734 },
  },
  {
    name: "VX Овна",
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
    position: { x: 344, y: 621 },
  },
  {
    name: "θ Персея",
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
    position: { x: 324, y: 677 },
  },
  {
    name: "α Печи",
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
    position: { x: 299, y: 723 },
  },
  {
    name: "ζ Сетки",
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
    position: { x: 355, y: 747 },
  },
  {
    name: "Гумбридж 1830",
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
    position: { x: 376, y: 791 },
  },
  {
    name: "HR 7722",
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
    position: { x: 487, y: 760 },
  },
  {
    name: "LP 944",
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
    position: { x: 392, y: 692 },
  },
  {
    name: "Вольф 489",
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
    position: { x: 375, y: 666 },
  },
  {
    name: "EQ Пегаса",
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
    position: { x: 435, y: 673 },
  },
  {
    name: "ξ Волопаса",
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
    position: { x: 461, y: 693 },
  },
  {
    name: "LHS 3003",
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
    position: { x: 546, y: 683 },
  },
  {
    name: "μ Кассиопеи",
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
    position: { x: 584, y: 716 },
  },
  {
    name: "γ Змеи",
    affiliation: Nations.Free,
    type: STAR_TYPE.Capital,
    position: { x: 444, y: 195 },
  },
];
