import { Nations } from "./nations";

export enum STAR_TYPE {
  Capital = "Столица",
  Controlled = "Контролируемая",
  Controversial = "Спорная",
}

export const Stars = [
  {
    name: "HD 7924",
    position: { x: 479, y: 58 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Кастор",
    position: { x: 581, y: 78 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Ι Часов",
    position: { x: 645, y: 50 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "ρ Кормы",
    position: { x: 675, y: 114 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "A 2329",
    position: { x: 698, y: 35 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Глизе 200",
    position: { x: 777, y: 18 },
    labelShift: { x: 0, y: 5 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "10 Гончих Псов",
    position: { x: 837, y: 84 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "37 Близнецов",
    position: { x: 888, y: 129 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Ψ Возмичего",
    position: { x: 823, y: 135 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "104 Тельца",
    position: { x: 812, y: 195 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Глизе 156",
    position: { x: 760, y: 152 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Глизе 818",
    position: { x: 743, y: 197 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "9 Кормы",
    position: { x: 970, y: 94 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "15 Стрелы",
    position: { x: 974, y: 163 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "β Кассиопеи",
    position: { x: 914, y: 237 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "10 Большой Медведицы",
    position: { x: 931, y: 297 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Глизе 247",
    position: { x: 974, y: 324 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "51 Пегаса",
    position: { x: 919, y: 357 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "η Волопаса",
    position: { x: 812, y: 368 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "β Девы",
    position: { x: 747, y: 363 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "δ Треугольника",
    position: { x: 779, y: 450 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "142 Скорпиона",
    position: { x: 713, y: 433 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Глизе 570",
    position: { x: 666, y: 453 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "36 Змееносца",
    position: { x: 675, y: 496 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Росс 104",
    position: { x: 661, y: 363 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Глизе 300",
    position: { x: 632, y: 325 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "107 Рыб",
    position: { x: 567, y: 313 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Σ Дракона",
    position: { x: 568, y: 373 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "70 Змееносца",
    position: { x: 610, y: 419 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "85 Пегаса",
    position: { x: 845, y: 536 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Capital,
  },
  {
    name: "111 Тельца",
    position: { x: 905, y: 554 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "G 239",
    position: { x: 812, y: 581 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "δ Козерога",
    position: { x: 824, y: 630 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "L 449 - 1",
    position: { x: 794, y: 679 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "11 Малого льва",
    position: { x: 752, y: 751 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Capital,
  },
  {
    name: "HR 6806",
    position: { x: 726, y: 295 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "β Волос Вероники",
    position: { x: 657, y: 206 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Демебола",
    position: { x: 526, y: 203 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Capital,
  },
  {
    name: "Грей μ",
    position: { x: 478, y: 146 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Мауна β",
    position: { x: 563.5, y: 181 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Глизе 532",
    position: { x: 588.5, y: 126 },
    affiliation: Nations.Imperium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Солнце",
    position: { x: 512, y: 512 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Capital,
  },
  {
    name: "α Центавра",
    position: { x: 530, y: 486 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Бернарда",
    position: { x: 561, y: 519 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Лаланд",
    position: { x: 497, y: 438 },
    labelShift: { x: 0, y: 2 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Росс 128",
    position: { x: 509, y: 416 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Вольф 359",
    position: { x: 483, y: 451 },
    labelShift: { x: -10, y: 0 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Сириус",
    position: { x: 439, y: 492 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Процион",
    position: { x: 413, y: 477 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Росс 614",
    position: { x: 398, y: 505 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Лакайль 5352",
    position: { x: 530, y: 613 },
    labelShift: { x: 5, y: -17 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Крюгер 60",
    position: { x: 552, y: 630 },
    labelShift: { x: 2.5, y: 2.5 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Лакайль 8760",
    position: { x: 590, y: 615 },
    labelShift: { x: 7.5, y: 5 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Альтаир",
    position: { x: 615, y: 589 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "61 Лебедя",
    position: { x: 573, y: 587 },
    labelShift: { x: 4, y: -4 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "ε Индейца",
    position: { x: 556, y: 604 },
    labelShift: { x: -5, y: 4 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Росс 154",
    position: { x: 589, y: 538 },
    labelShift: { x: 0, y: -7 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Струнве 2398",
    position: { x: 618, y: 543 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "κ Кита",
    position: { x: 748, y: 566 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Capital,
  },
  {
    name: "Глизе 667",
    position: { x: 671, y: 628 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "Фомальгаут",
    position: { x: 712, y: 611 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "π Ориона",
    position: { x: 730, y: 519 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "Каптейна",
    position: { x: 402, y: 540 },
    affiliation: Nations.TSF,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "ε Эридана",
    position: { x: 436, y: 559 },
    labelShift: { x: 7.5, y: 0 },
    affiliation: Nations.Nanotrasen,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "τ Кита",
    position: { x: 458, y: 584 },
    affiliation: Nations.Nanotrasen,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Гумбридж 34",
    position: { x: 507, y: 618 },
    labelShift: { x: -17.5, y: 0 },
    affiliation: Nations.Nanotrasen,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Ψ Змеи",
    position: { x: 265, y: 211 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Capital,
  },
  {
    name: "Глизе 282",
    position: { x: 266.5, y: 277 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "μ Жертвенника",
    position: { x: 226.5, y: 177 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Чалаван",
    position: { x: 321.5, y: 209.5 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "η Цефея",
    position: { x: 201, y: 243 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Глизе 488",
    position: { x: 683, y: 768 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Гумбридж 1831",
    position: { x: 658, y: 709 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "54 Рыб",
    position: { x: 608, y: 783 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "41 Жертвенника",
    position: { x: 491, y: 279 },
    affiliation: Nations.Unathi,
    type: STAR_TYPE.Capital,
  },
  {
    name: "HR 753",
    position: { x: 410, y: 302 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "AD Льва",
    position: { x: 402, y: 366 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "Глизе 1",
    position: { x: 445, y: 380 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "ADS 48",
    position: { x: 380, y: 246 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "G 192-13",
    position: { x: 363, y: 321 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "γ Зайца",
    position: { x: 270, y: 381 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Capital,
  },
  {
    name: "Тигардена",
    position: { x: 410, y: 410 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "HD 4391",
    position: { x: 352, y: 459 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Capital,
  },
  {
    name: "20 LMi",
    position: { x: 336, y: 567 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Capital,
  },
  {
    name: "Глизе 433",
    position: { x: 294, y: 587 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "HR 1614",
    position: { x: 295, y: 628 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "WISE 0325",
    position: { x: 239, y: 647 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "Глизе 902",
    position: { x: 163, y: 662 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "HOP 57050",
    position: { x: 261, y: 707 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "L 43-72",
    position: { x: 205, y: 732 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "41 Орла",
    position: { x: 242, y: 783 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "ν Феникса",
    position: { x: 296, y: 844 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "OU Близнецов",
    position: { x: 389, y: 838 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "Глизе 52",
    position: { x: 479, y: 854 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },
  {
    name: "Глизе 3825",
    position: { x: 542, y: 842 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Capital,
  },
  {
    name: "ν Волка",
    position: { x: 538, y: 799 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Controversial,
  },

  {
    name: "Арктур",
    position: { x: 202, y: 501 },
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Capital,
  },
  {
    name: "α Ворона",
    position: { x: 153, y: 612 },
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Capital,
  },
  {
    name: "Глизе 42",
    position: { x: 151, y: 449 },
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "DE Волопаса",
    position: { x: 211, y: 449 },
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "δ Эридана",
    position: { x: 286, y: 448 },
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "FL Водолея",
    position: { x: 274, y: 539 },
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "TRAPPIST 1",
    position: { x: 193, y: 569 },
    affiliation: Nations.Elysium,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "χ Ориона",
    position: { x: 410, y: 734 },
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Capital,
  },
  {
    name: "VX Овна",
    position: { x: 344, y: 621 },
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "θ Персея",
    position: { x: 324, y: 677 },
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "α Печи",
    position: { x: 299, y: 723 },
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "ζ Сетки",
    position: { x: 355, y: 747 },
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Гумбридж 1830",
    position: { x: 376, y: 791 },
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "HR 7722",
    position: { x: 487, y: 760 },
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "LP 944",
    position: { x: 392, y: 692 },
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "Вольф 489",
    position: { x: 375, y: 666 },
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "EQ Пегаса",
    position: { x: 435, y: 673 },
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "ξ Волопаса",
    position: { x: 461, y: 693 },
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "LHS 3003",
    position: { x: 546, y: 683 },
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "μ Кассиопеи",
    position: { x: 584, y: 716 },
    affiliation: Nations.CUSP,
    type: STAR_TYPE.Controlled,
  },
  {
    name: "γ Змеи",
    position: { x: 444, y: 195 },
    affiliation: Nations.Free,
    type: STAR_TYPE.Capital,
  },
];
